### ISSUE TITLE
Meteor 1.3 Integration

### ISSUE THREAD

**Issue by retotrinkler** [ethereumjs/ethereumjs-lib#125]
hi i'm trying to use JS modules of ethereumjs w Meteor 1.3. But get the same sha3 error in most of them (ethereumjs-account, keythereum, tx etc). 

Meteor install commands:

```
meteor create ethereum-app
cd ethereum-app
meteor npm install
meteor npm install --save ethereumjs-lib
```

but when using ethereumjs-lib from w/in meteor. Just copy the following line into main.js (for example):

`import EthereumjsLib from 'ethereumjs-lib';` 

and starting the meteor app with:

```
meteor
```

i get:

```
Unable to resolve some modules:

  "build/Release/sha3" in                     
/home/reto/ethereum-app/node_modules/ethereumjs-lib/node_modules/devp2p-dpt/node_modules/ethereumjs-util/node_modules/sha3/package.json
(web.browser)
```

does somebody have a idea on how to solve this?

**Comment by wanderer** [comment]
sorry I'm not really familiar with meteor.

**Comment by retotrinkler** [comment]
ok no problem. thanks anyway for your time

**Comment by retotrinkler** [comment]
Filed more appropriately here: https://github.com/axic/keccakjs/issues/1
